indicator: 'open_defecation'
country: 'Nigeria' # Should match the ADM0_NAME in the shapefile
iso3: 'NGA' # Capitalized ISO3 code
year: 2018
modeling_crs: 'EPSG:4326'
save_full_model: FALSE # Should the full INLA model be saved? Memory-intensive
shapefile_settings:
  modeling_level: 2
  ids:
    adm0: ['ADM0_CODE','ADM0_NAME']
    adm1: ['ADM1_CODE','ADM1_NAME','ADM0_CODE','ADM0_NAME']
    adm2: ['ADM2_CODE','ADM2_NAME','ADM1_CODE','ADM1_NAME','ADM0_CODE','ADM0_NAME']
covariate_settings:
  file_format: 'tif'
  add_intercept: TRUE
pop_covariate_settings:
  covariate: 'worldpop_total'
  annual: TRUE
  transform: 'identity'
  normalize: FALSE
stacking_settings:
  run_stacking: TRUE
  adm1_fixed_effects: TRUE
  submodels:
    enet:
    gam:
    gbm:
      verbose: FALSE
  cv:
    method: 'repeatedcv'
    number: 5
    repeats: 5
inla_settings:
  family: 'binomial'
  link: 'logit'
  sample_size_field: 'samplesize'
  effects:
    covariates: TRUE
    spde: TRUE
    nugget: TRUE
    admin1: FALSE
  mesh:
    integrate_to_zero: FALSE
    cutoff: 0.04
    max_edge: [0.02, 5]
  priors:
    range:
      threshold: 0.1
      prob_below: 0.05
    sigma:
      threshold: 1.5
      prob_above: 0.05
    fixed_effects:
      threshold: 1.0
      prob_above: 0.05
    nugget:
      threshold: 0.25
      prob_above: 0.01
    admin1:
      threshold: 1.0
      prob_above: 0.05
prediction_settings:
  n_samples: 250
  ui_width: 0.95
  nugget_in_predict: TRUE
  draws_link_function: 'plogis'
versions:
  results: 'v1'
directories:
  shps:
    versioned: FALSE
    path: '/FILE/PATH'
    files:
      adm0: 'g2015_2014_0.shp'
      adm1: 'g2015_2014_1.shp'
      adm2: 'g2015_2014_2.shp'
  raw_data:
    versioned: FALSE
    path: '/FILE/PATH'
    files:
      covariates_table: 'covariates_table.csv'
  covariates:
    versioned: FALSE
    path: '/FILE/PATH'
  results:
    versioned: TRUE
    path: '/FILE/PATH'
    files:
      adm_boundaries: 'adm_boundaries.shp'
      id_raster: 'id_raster.tif'
      covariate_rasters: 'covariate_rasters.tif'
      formatted_input_data: 'formatted_input_data.csv'
      inla_data_stack: 'inla_data_stack.RDS'
      inla_model: 'inla_fitted_model.RDS'
      parameter_draws: 'parameter_draws.RDS'
      cell_draws: 'cell_draws.csv'
      cell_pred_mean: 'cell_pred_mean.tif'
      cell_pred_lower: 'cell_pred_lower.tif'
      cell_pred_upper: 'cell_pred_upper.tif'
      counts_mean: 'counts_mean.tif'
      counts_without_mean: 'counts_without_mean.tif'
      adm2_draws: 'adm2_draws.csv'
      adm2_summary_table: 'adm2_summary_table.csv'
      adm1_draws: 'adm1_draws.csv'
      adm1_summary_table: 'adm1_summary_table.csv'
      adm0_draws: 'adm0_draws.csv'
      adm0_summary_table: 'adm0_summary_table.csv'
      pop_raster: 'pop_raster.tif'
      stacked_covariates: 'stacked_covariates.tif'
