#' Prepare data stack for INLA
#' 
#' @param input_data A data.frame with at least the following columns:
#'   - 'indicator': number of "hits' per site, e.g. tested positive for malaria
#'   - 'samplesize': total population sampled at the site
#'   - 'x': x position, often longitude
#'   - 'y': y position, often latitude
#' @param id_raster terra SpatRaster with non-NA pixels delineating the extent of the
#'   study area 
#' @param covariates (list) Named list of all covariate effects included in the model,
#'   typically generated by [load_covariates()].
#' 
#' @return List containing the following items:
#' 
#' @importFrom INLA inla.mesh.2d inla.spde2.matern inla.spde.make.A inla.stack
#' @importFrom data.table as.data.table
#' @importFrom terra extract
#' @export
prepare_inla_data_stack <- function(input_data, id_raster, covariates){
  # TODO Add validation

  id_raster_table <- data.table::as.data.table(id_raster, xy = TRUE) |> na.omit()

  # Build prediction mesh
  mesh <- INLA::inla.mesh.2d(
    loc.domain = id_raster_table[, .(x, y)],
    max.edge = c(0.1, 5),
    cutoff = 0.01
  )

  # SPDE object
  spde <- INLA::inla.spde2.matern(
    mesh = mesh,
    alpha = 2,
    constr = TRUE
  )

  # Spatial index
  index_space <- INLA::inla.spde.make.index(name = "space", n.spde = spde$n.spde)

  # Projection matrix: mesh to data
  A_proj_data <- INLA::inla.spde.make.A(
    mesh = mesh,
    loc = as.matrix(input_data[, .(x, y)])
  )

  # Extract all covariates
  cov_names <- names(covariates)
  for(cov_name in cov_names){
    input_data[[cov_name]] <- terra::extract(
      x = covariates[[cov_name]],
      y = as.matrix(input_data[, .(x, y)])
    )[, 1]
  }

  # Data stack for estimation
  inla_data_stack <- INLA::inla.stack(
    tag = 'est',
    data = list(y = input_data$indicator, samplesize = input_data$samplesize),
    A = list(1, A_proj_data),
    effects = list(input_data[, ..cov_names], s = index_space)
  )

  # INLA model formula
  formula_string <- paste(
    'y ~ 0 +', paste(cov_names, collapse = ' + '), '+ f(space, model = spde)'
  )

  data_list <- list(
    mesh = mesh,
    spde = spde,
    inla_data_stack = inla_data_stack,
    formula_string = formula_string
  )

  return(data_list)
}
